name: alphafold 
channels:
  - nvidia
  - pytorch  # Add the PyTorch channel
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pytorch
  - torchvision
  - matplotlib
  - cpuonly
  - ipykernel
  - modelcif
  - pip 
  - ffmpeg
  - py3dmol
  - nbformat
  - nbconvert
  - transformers
  - lightning
  - datasets
  - tensorboard